### ISSUE TITLE
[請求] 功能改名

### ISSUE THREAD

**Issue by nk980113** [Gary50613/yeecord-project#17]
**什麼是需要請求的:**
把支援伺服器的支票(ticket)系統改名為私人頻道系統
**為什麼會需要這個請求:**
~~不然在支援伺服器的人會以為自己欠凱恩錢~~

**Comment by Gary50613** [comment]
好哦會在下一個版本更改 😂

**Comment by Gary50613** [comment]
在 [dc75e92](https://github.com/Gary50613/yeecord/commit/dc75e92b854cbb41deecd9b07b44dbd8cdec2562) 被修復了
