### ISSUE TITLE
[請求]投票換邊

### ISSUE THREAD

**Issue by nk980113** [Gary50613/yeecord-project#20]
**什麼是需要請求的:**
投票可以再換別的選項投，不知道為什麼一直沒出這功能
**為什麼會需要這個請求:**
1.如果投票不小心按錯就尷尬了
2.投完之後發現自己其實是被帶風向所以想反悔

相信凱恩做得到，連在投票中投了什麼都能抓到了

**Comment by kane50613** [comment]
只是可能需要個速率限制(?

**Comment by nk980113** [comment]
好喔
同意

**Comment by kane50613** [comment]
這個窩們解決好了哦

現在可以有更多自定義選項
