### ISSUE TITLE
[漏洞] 伐木工不可選

### ISSUE THREAD

**Issue by charliie-dev** [Gary50613/yeecord-project#21]
**描述這個漏洞:**
"伐木工"沒有出現在工作選單內。
**怎麼重現這個錯誤:**
&job
**預期要發生的事情:**
出現伐木工選項
**截圖:**
![image](https://user-images.githubusercontent.com/32497323/163925147-dbcbf2d6-44c5-4c27-88ec-b83c836fd8be.png)

**伺服器連結或ID:**
894569922422767616

**Comment by kane50613** [comment]
目前伐木工會等到和冒險一起出哦

**Comment by charliie-dev** [comment]
ok, 感謝!
