### ISSUE TITLE
[漏洞]不能進入群組

### ISSUE THREAD

**Issue by CocaColaCocaCola** [Gary50613/yeecord-project#22]
**描述這個漏洞:**
雖然有邀請,但是不能加入
**怎麼重現這個錯誤:**
重新再按邀請
**預期要發生的事情:**

**截圖:**

**伺服器連結或ID:**

**Comment by CocaColaCocaCola** [comment]
Any body help me??

**Comment by seven-317** [comment]
進入什麼群組
你是說機器龍進不去你的群組還是你進不來Yeecord Community
如果是進不來Yeecord 的話請附上Discord名稱&tag

**Comment by CocaColaCocaCola** [comment]
是yeecord
Harold1#2119

**Comment by seven-317** [comment]
https://discord.gg/JdeTjPRu
https://discord.gg/yeecord
兩個網址都試試看

**Comment by CocaColaCocaCola** [comment]
我登入後想登小帳登不了,是有甚麼設定嗎?

**Comment by seven-317** [comment]
你需要驗證你的電子郵件並啟用2FA安全認證

**Comment by CocaColaCocaCola** [comment]
我驗證了也不能😭😭😭😭😭
