### ISSUE TITLE
[漏洞]使用教學文字勘誤

### ISSUE THREAD

**Issue by wzsayhi** [Gary50613/yeecord-project#23]
**描述這個漏洞:**
使用教學文字勘誤 [民生工作#詳細資料](https://yeecord.com/docs/rpg/jobs/#%E8%A9%B3%E7%B4%B0%E8%B3%87%E6%96%99)

農夫
X 飽石度
O 飽食度

**怎麼重現這個錯誤:**
歡迎去看看(?

**預期要發生的事情:**
我要看到飽食度!

**截圖:**
![image](https://user-images.githubusercontent.com/16789173/164710075-23d52c93-a7cf-4812-903c-5fd0f878374a.png)

**伺服器連結或ID:**
N/A

**題外話**
沒有找到官網的Repo，不然我就改完直接發PR了

**Comment by kane50613** [comment]
錯字被修復好了 ✅
