### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by sowhatqqOAO** [Gary50613/yeecord-project#24]
**描述這個漏洞:**
機器人會自動卡歌，並跳出群組
**怎麼重現這個錯誤:**
放一個一小時以上的曲子影片
**預期要發生的事情:**
正常播放且完整放完
**截圖:**
無
**伺服器連結或ID:**
https://discordapp.com/channels/608541819290255363/934768730829910068

**Comment by kane50613** [comment]
可能是剛剛正在進行重新啟動，請問過幾分鐘之後播放正常了嗎？

**Comment by sowhatqqOAO** [comment]
今天發生蠻多次的請問今天重啟很多次嗎?

**Comment by kane50613** [comment]
> 今天發生蠻多次的請問今天重啟很多次嗎?

那請問是馬上一播放就跳出去嗎

**Comment by sowhatqqOAO** [comment]
偶發性的但就是撥放到一半直接卡歌過一陣子機器人就跳掉，或者機器人的歌單會不見
