### ISSUE TITLE
[請求]新增音樂相關的指令

### ISSUE THREAD

**Issue by ghost** [Gary50613/yeecord-project#25]
希望可以新增刪除佇列中的某一首音樂
因為有時會不小心點錯，但只能等輪到他才能跳過

以及單曲的快進(forward 跳秒數)
有些因為的前奏過長，希望可以跳過

**Comment by kane50613** [comment]
刪除一首點錯的音樂可以使用 `&remove 曲號` 的指令

`&q` 可以查看曲號
