### ISSUE TITLE
[漏洞] dvc rename

### ISSUE THREAD

**Issue by flyingcatt3** [Gary50613/yeecord-project#7]
**描述這個漏洞: **
dvc rename後仍為預設命名格式

**怎麼重現這個錯誤: **
&dvc rename <anything>

**預期要發生的事情: **
dvc will be renamed

**截圖: **
![image](https://user-images.githubusercontent.com/41056055/141696625-0c423c44-7066-4b16-a95f-b2c38cbda74c.png)

**伺服器連結或ID: **
discord.gg/4YxrC2X

**Comment by Gary50613** [comment]
目前確認bug已經被修復，可以再嘗試改名一次嗎

**Comment by flyingcatt3** [comment]
改名成功
