### ISSUE TITLE
跨群聊天 [漏洞]

### ISSUE THREAD

**Issue by ItJamesplay** [Gary50613/yeecord-project#9]
**描述這個漏洞: **
編輯時其他何服器不會一起更改
**怎麼重現這個錯誤: **
在一個何服器編輯訊息另一個何服器會看到初始訊息
**預期要發生的事情: **
訊息不會編輯
**截圖: **
![D3715368-09B4-42B6-A987-96FAD24B144B](https://user-images.githubusercontent.com/39452289/148045140-a0f53fcd-c036-49a5-8b8e-8159db82d367.png)
![E61BE2BE-619A-44DB-9894-943E0D7CBD49](https://user-images.githubusercontent.com/39452289/148045152-d8d33d59-0cd8-4351-aa3b-1f3f357883b4.png)

**伺服器連結或ID: **
discord.gg/cwrq9rm

**Comment by Gary50613** [comment]
修好惹
